### ISSUE TITLE
Failure to see the resizer toolbar

### ISSUE THREAD

**Issue by howardm** [oobianom/r2resize#1]
In a Quarto document, I have the following: 

```
---
title: "Imaging of lung edema"
filters:
  - lightbox
author: "Howard Mann"
date: "2023-01-15"
description: "In this introduction to imaging features of lung edema I will distinguish primarily between *hydrostatic* and *acute lung injury* edema, and explain under what circumstances it may be difficult to determine which is present without clinical context."
image: thumbnail.jpg
page-layout: full
---

`library(r2resize)`

`r2resize::add.resizer()`

```

The above is printed in the output.

Nothing else happens.

I'm clearly naive and doing something wrong.

What is it ?

Cheers.

**Comment by howardm** [comment]
Update:

I tried the following:

````
```{r eval=TRUE, message=TRUE, include=FALSE}
library(r2resize)
```

```{r echo=FALSE, include=FALSE}
r2resize::add.resizer()
```
````

And then restarted the R session (I'm using RStudio).

I got the following:

```

Restarting R session...

> library(r2resize)
Registered S3 methods overwritten by 'htmltools':
  method               from         
  print.html           tools:rstudio
  print.shiny.tag      tools:rstudio
  print.shiny.tag.list tools:rstudio
Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio
> r2resize::add.resizer()
```

I don't know if this is a clue to explain why it's not working for me.

Howard

**Comment by howardm** [comment]
An update:

As I'm using Quarto, I tried :

````
```{r}
#| eval: true
#| include: false
library(r2resize)
```
````
And

````

```{r}
#| include: false
r2resize::add.resizer()
```

````
Nothing happens.

**Comment by oobianom** [comment]
Hey Howard, I will address this as soon as possible and get you a feedback by this week. Are you having the issue just in Quarto or also when using Rmarkdown?

**Comment by howardm** [comment]
I experience this when using Quarto.

Thanks.

**Comment by oobianom** [comment]
I have a resolution for you. At this moment, r2resize will not work for images with caption. I will have this resolve in the upcoming version. Just make sure that your figures do not include captions for version 1.4 to work. Make sure to include images and tables to see the effect. Below is a refinement to your code
```
---
title: "Imaging of lung edema"
filters:
  - lightbox
author: "Howard Mann"
date: "2023-01-15"
description: "In this introduction to imaging features of lung edema I will distinguish primarily between *hydrostatic* and *acute lung injury* edema, and explain under what circumstances it may be difficult to determine which is present without clinical context."
image: thumbnail.jpg
page-layout: full
---

```{r}
# call the r2resize library
library(r2resize)

#include the resizer
r2resize::add.resizer()

``

# Add a figure (works because no caption is included)

```{r}
#| label: fig-airquality
#| warning: false
library(ggplot2)
ggplot(airquality, aes(Temp, Ozone)) +
  geom_point() +
  geom_smooth(method = "loess")
``


# another image (doesn't work because caption is included)

```{r}
#| label: fig-airquality1
#| fig-cap: Temperature and ozone level.
#| warning: false
ggplot(airquality, aes(Temp, Ozone)) +
  geom_point() +
  geom_smooth(method = "loess")
``

# Add a table (works as well)

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |


# Data tables (works as well)

```{r}
library(DT)
datatable(iris)
``

```

**Comment by howardm** [comment]
Hi,

I don't have any figures/plots like you describe above in the document.

I have images inserted as, for example:

`![](images/CXR.jpg)`

I do have a few simple tables as you describe.

Nothing happens when I save (and render) the document.

I do see the following in the resultant html page:

![Screen Shot 2023-01-30 at 12 06 51 PM](https://user-images.githubusercontent.com/6101226/215571977-f93a0861-6b65-4208-b49c-2b58d6e541c9.jpg)

Howard

**Comment by oobianom** [comment]
Yes it does work for that sort of declaration of image. I just checked in my R 4.1.2 environment. The code below works. Perhaps, you can share your full code and we can take a look.

Here is the QMD file -> [sample](https://obianom.com/SAMPLE.qmd)

**Comment by howardm** [comment]
Here you are:

https://www.dropbox.com/sh/i3qphcsrgzpjj0j/AAA7-iQh47k7shDASDABxFBIa?dl=0

I don't presently have the resizer code in it.

**Comment by oobianom** [comment]
I added the resizer in it and it rendered well
https://obianom.com/qmd_lung_edema_requisites.zip

**Comment by howardm** [comment]
Sorry.

Nothing happens when I try it.

I presume, again, I should see the toolbars within the Rstudio editing panel.

Here's a screenshot:

![Screen Shot 2023-01-30 at 1 26 43 PM](https://user-images.githubusercontent.com/6101226/215587632-99abb30e-4610-45ec-bc88-da27b4f70162.jpg)


Howard

**Comment by oobianom** [comment]
Oh no, that's the confusion, I see. You will not see any effect in RStudio, but you will after you render the document and produce an HTML. Look at one of the example outputs - https://rstudio-pubs-static.s3.amazonaws.com/977399_37ed43a251fe493d87efe81c452b7f7d.html

**Comment by howardm** [comment]
O.K.

I don't see anything in the resultant HTML file in a browser, either.

Here's a screenshot:

![Screen Shot 2023-01-30 at 6 59 50 PM](https://user-images.githubusercontent.com/6101226/215640566-ac948e01-f237-4a6c-91ea-4874771c677b.jpg)

By the way, I obviously misunderstand the whole point of this package.

Please explain it in simple terms.

In a reply above, you say: "I added the resizer in it and it rendered well."

Please post a screenshot of what you saw. 

Thanks.

**Comment by cpsyctc2** [comment]
I think I have the same problem 

I am using  4.3.3 (2024-02-29) -- "Angel Food Cake" and r2resize v.1.9 from CRAN.

[This code](https://www.psyctc.org/r2resize2.Rmd) (Sorry about link but pasting code into these dialogues always mangles it for me).  That just produces [this HTML](https://www.psyctc.org/r2resize2.html) with no resizer bar and no error messages.  

If I pull the zip package above and try to render the Quarto code I get this error message:

> Error running filter /usr/lib/rstudio/resources/app/bin/quarto/share/filters/main.lua:
Error running filter /media/chris/Clevo_SSD2/Data/MyR/R/qmd_lung_edema_requisites/lightbox:
Could not find executable /media/chris/Clevo_SSD2/Data/MyR/R/qmd_lung_edema_requisites/lightbox
stack traceback:
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:4030: in function <.../rstudio/resources/app/bin/quarto/share/filters/main.lua:4009>
	[C]: in ?
	[C]: in method 'walk'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:449: in local 'callback'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:495: in function <.../rstudio/resources/app/bin/quarto/share/filters/main.lua:476>
stack traceback:
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:449: in local 'callback'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	.../rstudio/resources/app/bin/quarto/share/filters/main.lua:495: in function <.../rstudio/resources/app/bin/quarto/share/filters/main.lua:476>

I hope you can suggest what is going wrong, TIA, Chris

**Comment by oobianom** [comment]
Hi Chris, please take a look at this thread (https://github.com/oobianom/r2resize/issues/2) where I addressed a similar issue. Let me know if it resolves your question. If not, I will look into your case specifically.

**Comment by cpsyctc2** [comment]
Thanks Obi, I have added to (https://github.com/oobianom/r2resize/issues/2) to clarify that one issue is that the block that initialises JQuery must not be an `include=FALSE` block.  That seems to have been what was causing my use of the resizer to fail.  Thanks!
