### ISSUE TITLE
Setting images, tables to FALSE does not remove resize bar

### ISSUE THREAD

**Issue by belinskyc** [oobianom/r2resize#3]
Hi there,

I still get toolbars on images and table after I set `tables `and `images `to `FALSE `in `add.resizer()`.

I am using R 4.3.2, RStudio 2023.12.1 (402), Quarto 1.4.533, Windows 11

thanks again,
Charlie

```
---
title: "test r2resize"
format: html
---

```{r pressure1}
library(DT)
library(r2resize)

add.resizer(
  tables = FALSE,   
  images = FALSE
)

plot(mtcars)
datatable(iris)
```

Once again, sorry, the final line in the codeblock should be \`\`\`

**Comment by oobianom** [comment]
Thanks Charlie. I made an update to the script and committed to this repository. It works now.
```
remotes::install_github("oobianom/r2resize")
```

I am also preparing a version to deploy to CRAN. This will be included as well.

**Comment by belinskyc** [comment]
Looks good -- thank you much!
